services:
  laravel_backend:
    build:
      context: ./backend
    container_name: laravel_backend
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - postgres_db

  angular_frontend:
    build:
      context: ./frontend
    container_name: angular_frontend
    volumes:
      - ./frontend:/app
      - angular_node_modules:/app/node_modules
    working_dir: /app
    command: npm start
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist/${APP_NAME}:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - angular_frontend

  postgres_db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
  angular_node_modules:
